repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
      files: "^./setup.py"
-   repo: local
    hooks:
    - id: export_requirements
      name: export_requirements
      entry: "poetry export -f requirements.txt > requirements.txt"
      language: system
      files: "./requirements.txt"
