version: '3.2'

services:
  sidewalkscore:
    build: ..
    command: bash -c "poetry run sidewalkscore build --changes-sign incline /config && poetry run sidewalkscore weight /config && poetry run sidewalkscore score -o sidewalkscore.geojson -od GeoJSON /config"
    volumes:
      - ./data/sidewalkscore:/config:rw
