version: '3.2'

services:
  unweaver:
    build: ./dockerfiles/unweaver
    command: poetry run unweaver run /data -h 0.0.0.0 -p 5656
    ports:
      - 5656:5656
    environment:
      - SERVER_PORT=5656
    volumes:
      - ./build/router:/data:ro

  unweaver_streets:
    build: ./dockerfiles/unweaver
    command: poetry run unweaver run /data -h 0.0.0.0 -p 5657
    ports:
      - 5657:5657
    environment:
      - SERVER_PORT=5657
    volumes:
      - ./build/router_streets:/data:ro

  caddy:
    image: abiosoft/caddy:0.11.5-no-stats
    ports:
        - 2015:2015
    environment:
        - HOST=localhost
    volumes:
      - ./config/caddy/Caddyfile:/etc/Caddyfile:ro
      - ./build/tiles:/tiles:ro
      - ./build/webapp:/webapp
    links:
      - unweaver
      - unweaver_streets
