version: '3.2'

services:
  tippecanoe_transportation:
    build: https://github.com/mapbox/tippecanoe.git#1.33.0
    entrypoint: sh /build_tiles.sh /home/tippecanoe/input /home/tippecanoe/output http://localhost:2015
    volumes:
      - ./config/tippecanoe/build_tiles.sh:/build_tiles.sh:ro
      - ./config/tippecanoe/pedestrian-tilejson.json:/home/tippecanoe/pedestrian.json:ro
      - ./data/transportation.geojson:/home/tippecanoe/input/transportation.geojson:ro
      - ./build/tiles:/home/tippecanoe/output:rw

  tippecanoe_sidewalkscore:
    build: https://github.com/mapbox/tippecanoe.git#1.33.0
    entrypoint: sh /build_tiles.sh /home/tippecanoe/input /home/tippecanoe/output http://localhost:2015
    volumes:
      - ./config/tippecanoe_sidewalkscore/build_tiles.sh:/build_tiles.sh:ro
      - ./config/tippecanoe_sidewalkscore/sidewalkscore-tilejson.json:/home/tippecanoe/sidewalkscore.json:ro
      - ./data/sidewalkscore/sidewalkscore.geojson:/home/tippecanoe/input/sidewalkscore.geojson:ro
      - ./build/tiles:/home/tippecanoe/output:rw

  webapp:
    build:
      ../webapp
    command: npm run build
    environment:
      - REACT_APP_MAPBOX_TOKEN=$WALKSHED_MAPBOX_TOKEN
      - REACT_APP_TILESERVER=/tiles
      - REACT_APP_ROUTESERVER=/api/routing
    volumes:
      - ./build/webapp:/www/build
